version: '3.9' # Specify the Docker Compose version

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/certs:/etc/nginx/ssl
            - ./dist:/usr/share/nginx/html
        ports:
            - 80:80
            - 443:443
        restart: always
